package com.shivray.cargo.reports;

import com.lowagie.text.Cell;
import com.lowagie.text.Document;
import com.lowagie.text.FontFactory;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Table;
import com.lowagie.text.pdf.PdfWriter;

import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.util.List;

public final class PdfReports {

    private PdfReports() {
    }

    public static void generate(String title, List<Object[]> rows) throws Exception {

        Path dir = Paths.get("reports");
        Files.createDirectories(dir);

        String safe = title.replaceAll("[^A-Za-z0-9]+", "_");

        Path file = dir.resolve(
                safe + "_" + System.currentTimeMillis() + ".pdf"
        );

        Document document = new Document(PageSize.A4.rotate());

        try (OutputStream output = Files.newOutputStream(file)) {

            PdfWriter.getInstance(document, output);

            document.open();

            document.add(
                    new Paragraph(
                            "SHIVRAY INTERNATIONAL",
                            FontFactory.getFont(
                                    FontFactory.HELVETICA_BOLD,
                                    20
                            )
                    )
            );
            

            document.add(
                    new Paragraph(
                            "Air Cargo Management System"
                    )
            );

            document.add(
                    new Paragraph(
                            title + " | Generated: "
                                    + LocalDateTime.now()
                    )
            );

            document.add(new Paragraph(" "));

            if (rows != null && !rows.isEmpty()) {

                int columnCount = rows.get(0).length;

                Table table = new Table(columnCount);
                table.setWidth(100);

                for (int i = 0; i < columnCount; i++) {

                    table.addCell(
                            new Cell(
                                    "Field " + (i + 1)
                            )
                    );
                }

                for (Object[] row : rows) {

                    for (Object value : row) {

                        table.addCell(
                                new Cell(
                                        value == null
                                                ? ""
                                                : String.valueOf(value)
                                )
                        );
                    }
                }

                document.add(table);

            } else {

                document.add(
                        new Paragraph(
                                "No records found."
                        )
                );
            }

            document.add(
                    new Paragraph(
                            "Generated by Shivray International Air Cargo System"
                    )
            );

            // IMPORTANT:
            // Close the PDF document BEFORE the output stream closes.
            document.close();
        }

        System.out.println(
                "PDF generated: " + file.toAbsolutePath()
        );
    }
}